# Generated by Django 5.1.6 on 2025-04-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0002_problemgenre_remove_problem_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starting_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='contests', to='competition.contestgenre')),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=100, help_text='Points awarded for solving this problem')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the problem in the contest')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', through='competition.ContestProblem', to='problem.problem'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('submissions_count', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'last_submission_time'],
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(related_name='participated_contests', through='competition.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
