# Generated by Django 5.1.6 on 2025-03-10 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_time", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("last_submission_time", models.DateTimeField(blank=True, null=True)),
                ("submissions_count", models.IntegerField(default=0)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "last_submission_time"],
                "unique_together": {("user", "contest")},
            },
        ),
        migrations.AddField(
            model_name="contest",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_contests",
                through="competition.Participation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
