# Generated by Django 5.1.6 on 2025-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
