# Generated by Django 5.1.6 on 2025-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_contest_difficulty_contest_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='max_participants',
        ),
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
