# Generated by Django 5.1.6 on 2025-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the question", max_length=200),
                ),
                ("question", models.TextField(help_text="Question content")),
                (
                    "answer",
                    models.TextField(help_text="Correct answer for the question"),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Category or genre of the question", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
