# Generated by Django 5.1.6 on 2025-03-31 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="problem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="problem",
            name="creator",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_problems",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="eval_type",
            field=models.IntegerField(
                default=0,
                help_text="Evaluation type: 0 for code, 1 for text, 2 for no auto eval",
            ),
        ),
        migrations.RemoveField(
            model_name="problem",
            name="genre",
        ),
        migrations.AddField(
            model_name="problem",
            name="genre",
            field=models.ManyToManyField(
                related_name="problem", to="problem.problemgenre"
            ),
        ),
    ]
