# Generated by Django 5.2 on 2025-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0, help_text='Score of the submission'),
        ),
    ]
